### ISSUE TITLE
ImportError: cannot import name 'url' from 'django.conf.urls' on Django 4.0

### ISSUE THREAD

**Issue by FriedrichFroebel** [and3rson/django-searchable-select#34]
I discovered your project today while researching some stuff and tried to include it into my project. This failed as Django 4.0 removed the `django.conf.urls.url` method which had been deprecated in Django 3.0.

For this reason I am currently using a workaround in my `urls.py` file:

```python
from django.urls import path, include
from searchableselect.views import filter_models as searchable_select_filter_models

urlpatterns = [
    # Original solution does not work for Django 4.0.
    # path("searchableselect/", include("searchableselect.urls")),
    path(
        "searchable-select/",
        searchable_select_filter_models,
        name="searchable-select-filter",
    ),
]
```

As far as I have seen, the other functionality seems to work with Django 4.0.

**Comment by MicheleTsigab** [comment]
It is because django.urls.url is deprecated since django 4.0, 
Instead Go to 'path/to/searchableselect/urls.py' and 
use from django.urls import re_path, also change url('^filter....) to re_path('^filter..)
